{% set data= load_setup_py_data() %}
package:
  name: ts-hop-client
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: generic
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - run_hop_producer = lsst.ts.hop.client:run_hop_producer

test:
  requires:
    - ts-conda-build =0.3
    - ts-salkafka
    - hop-client
  source_files:
    - pyproject.toml
    - python
    - setup.cfg
    - tests
  commands:
    - pytest

requirements:
  host:
    - pip
    - python {{ python }}
    - setuptools
    - setuptools_scm
  build:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - ts-conda-build =0.3
  run:
    - python {{ python }}
    - hop-client
    - ts-salkafka